language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"

matrix:
    allow_failures:
        - perl: "5.16"

env:
  - PERL_MM_USE_DEFAULT=1

install:
  - perl Makefile.PL
  - cpanm --installdeps .

script:
  - make test -j4
